const store = [
  {
    title: 'Para dias más productivos',
    description: 'Agendas y bullet journals',
    date: '2020-02-18',
    img_url: 'https://res.cloudinary.com/robcar/image/upload/v1613786388/image_7_teaj7e.png',
    size: '',
  },
  {
    title: 'Para IOS',
    description: 'Intereses, el nuevo Widget de Pinterest',
    date: '2020-02-18',
    img_url: 'https://res.cloudinary.com/robcar/image/upload/v1613786730/image_2_fhq6jo.png',
    size: '',
  },
  {
    title: 'Gafas de Sol',
    description: 'Un accesorio que no puede faltar en tu look',
    date: '2020-02-18',
    img_url: 'https://res.cloudinary.com/robcar/image/upload/v1613786735/image_1_cyn7va.png',
    size: 'large',
  },
  {
    title: 'Un viaje por la arquitectura mexicana',
    description: 'Estilo colonial y moderno',
    date: '2020-02-17',
    img_url: 'https://res.cloudinary.com/robcar/image/upload/v1613786974/torres_4.png',
    size: '',
  },
  {
    title: 'Espejos con mucho estilo para tu casa',
    description: 'Ideas para decorar',
    date: '2020-02-17',
    img_url: 'https://res.cloudinary.com/robcar/image/upload/v1613787059/decorar_5.png',
    size: '',
  },
  {
    title: 'Cómo utilizarla para un mundo mejor',
    description: 'Inteligencia Artificial',
    date: '2020-02-17',
    img_url: 'https://res.cloudinary.com/robcar/image/upload/v1613787090/ia_6.png',
    size: '',
  },
  {
    title: 'Por dias más productivos',
    description: 'Agendas y bullet journals',
    date: '2020-02-17',
    img_url: 'https://res.cloudinary.com/robcar/image/upload/v1613787095/agenda_7.png',
    size: '',
  },
]